### ISSUE TITLE
Modify margins

### ISSUE THREAD

**Issue by kugulus** [novoid/LaTeX-KOMA-template#10]
First of all: Thank you for this great template, it's really useful!

But I would like to modify the margins, because in my opinion they are a bit too large. My problem is, that I can't find out how to do so... Could you help me?

Thank you!

**Comment by stefanbschneider** [comment]
This answers the question quite well: https://tex.stackexchange.com/a/35820/52398

Set `DIV` in document class, eg,
```
\documentclass[fontsize=13pt,DIV=14]{scrreprt}
```
Larger values lead to larger text areas and smaller margins.
Default for 11pt is DIV=10 in KOMA.

**Comment by stefanbschneider** [comment]
Watchout, changing  DIV broke my document: Now figures and tables overlap sometimes!

**Comment by novoid** [comment]
I recommend to leave the defaults or use a specific package like [savetrees](https://ctan.org/pkg/savetrees?lang=en) which clearly aims at use-cases where legibility is no criteria any more.
