### ISSUE TITLE
scrpage2 obsolete

### ISSUE THREAD

**Issue by johannesbottcher** [novoid/LaTeX-KOMA-template#11]
Just came here via [TeX.SX](http://tex.stackexchange.com/q/232061/37907). 

Your template uses the (for a while now) obsolete `scrpage2`. Can you update the template to use `scrlayer-scrpage`?

**Comment by novoid** [comment]
Thanks for the pointer to the discussion. I'll have a look.

**Comment by novoid** [comment]
My GNU/Linux Debian stable does not come with scrlayer-scrpage yet.

Is there a negative effect when I wait a little longer in order to let "scrlayer-scrpage" to "sink in"?

**Comment by johannesbottcher** [comment]
Ah, Debian stable ;-) 
No, if your users use the documentaiton that is installed as well, there should be no disadvantages. 

For the last two versions i think, KOMA does not mention `scrpage2` anymore. The new package is backwards compatible, so there should be no real trouble changing in the future.

**Comment by novoid** [comment]
> Ah, Debian stable ;-) 

Yes, with all of its advantages and disadvantages :-)

However, Debian stable represents the (outdated) versions which are used in the wild. Many volks have issues with something "ultra-modern" like biblatex/biber and such. I have to be careful not to depend on versions people do not have (yet).

> No, if your users use the documentaiton that is installed as well, there should be no disadvantages. 

OK, then I'll mark this issue as closed and migrate in a couple of months.

> For the last two versions i think, KOMA does not mention `scrpage2` anymore. The new package is backwards compatible, so there should be no real trouble changing in the future. 

Good to know. Did happen after I stopped using LaTeX on a daily basis.
