### ISSUE TITLE
extra white space in figure environments using `myfig` macro

### ISSUE THREAD

**Issue by johannesbottcher** [novoid/LaTeX-KOMA-template#12]
Hi guys, 

a `center` environment (as used in `myfig`)will always add white space, additionaly to the white space that is introduced with the float. Is this *by design* in your template, or *by accident* as this is seldomly wanted. 

A little MWE for better understanding: 
```latex
\documentclass[twocolumn]{article}
\usepackage{showframe}
\begin{document}
\begin{figure}
	\begin{center}
\rule{2cm}{3cm}
\end{center}
\end{figure}
\noindent\rule{\linewidth}{.4pt}

\newpage
\begin{figure}
\centering
\rule{2cm}{3cm}
\end{figure}
\noindent\rule{\linewidth}{.4pt}
\end{document}
```

The same amount of white space will be introduced *above* the figure if floating at the bottom.

**Comment by novoid** [comment]
Hi Johannes!

You are absolutely right: This is a mistake I did not notice until now. I've corrected myfig to use the centering command instead the center environment.

Thanks for pointing this out!
