### ISSUE TITLE
Hyphenation with german words containing umlauts

### ISSUE THREAD

**Issue by daun20** [novoid/LaTeX-KOMA-template#13]
Hi, I do have a problem regarding hyphenation of words containing german umlauts:

I'm writing my masterthesis in german and some words with umlauts are not correctly hyphenated. I have changed the language order to \newcommand{\mylanguage}{american, ngerman} in main.tex and added \usepackage[T1]{fontenc} directly on top of the inputenc definition in preample.tex. With activated T1 I get ugly headings, is there a problem with T1 and the mathpazo package?

Without T1 I can't define manual hyphenations in main.tex for words with umlauts. For example "Gummioberfläche" is always hyphenated as "Gummio-berfläche".

What would be the best way to define hyphenations for german words with umlauts and not changing heading fonts?

Thanks in advance!

**Comment by Findus23** [comment]
Hallo, 
I wrote my "Vorwissenschaftliche Arbeit" using this template:
https://github.com/Findus23/VWA
I had no issues with hyphenation (although I changed the parameters to make them fewer: https://github.com/Findus23/VWA/blob/master/main.tex#L245-L250 ).
I also added T1 without problems: (I added it directly after document class) https://github.com/Findus23/VWA/blob/master/template/preamble.tex#L383-L384

**Comment by daun20** [comment]
Hi and thanks for your reply! There are just some words that are incorrectly hyphenated, most of the time it works really well. Therefor I have to use T1 to define some special words with umlauts in main.tex. I solved it temporarly by including the lmodern package at the end of the preamble (in addition to T1), although I'm not aware if that's a good solution. Now I can enter manual hyphenations with umlauts and the font in my PDF looks exactly the same as before, nobmore ugly headings.

**Comment by novoid** [comment]
If I understand correctly, you are using English and German language in your document.

Did you switch languages properly? `\begin{otherlanguage}{ngerman}...\end{otherlanguage}` or `\foreignlanguage{ngerman}{Gummioberfläche}`

**Comment by daun20** [comment]
Hi, I'm writing my thesis in german, american is just for the affidavit
(former statuary declaration). The language in main.tex is set with the
command \newcommand{\mylanguage}{american,ngerman}. For the english part of
the affidavit I'm using \foreignlanguage{american}{...}, for the rest of
the document ngerman should be active as default I think...

2015-05-24 11:26 GMT+02:00 novoid <notifications@github.com>:

**Comment by novoid** [comment]
OK, your setup looks OK.

AFAIR I had issues when using T1 by myself and therefore I disabled it.

As a workaround, you could define a macro for Gummioberfläche: `\newcommand{\GO}{Gummi\-ober\-fläche}` which should do the trick.

Since this does not seem to be an issue directly related to this template, I am going to close this issue for now. Sorry when I could not help you to solve your issue without a workaround.
