### ISSUE TITLE
Xelatex/lualatex support?

### ISSUE THREAD

**Issue by krishnakumarg1984** [novoid/LaTeX-KOMA-template#20]
Does this template support Xelatex or lualatex?

Also, is continuous building using ```latexmk``` feasible?

**Comment by novoid** [comment]
Hi @krishnakumarg1984,

You won't get those features from me unfortunately. So I'm going to close this issue for now.

If you are going to fork, keep the attribution and implement them on your own, I am happy to link your repo from here.
