### ISSUE TITLE
Margins for two-sided printing flipped?

### ISSUE THREAD

**Issue by stefanbschneider** [novoid/LaTeX-KOMA-template#35]
Thanks for the nice template!

I'm a bit confused about the page margins (left and right)with the `twoside` mode.
My understanding is that the first/title page as well as all new chapter beginnings (and any odd page numbers) should be on the right side of the book (when reading the printout).
This would mean that book's binding is on the left side of the page, which I thought, is what the larger margin is for.
But the larger page margin is on the right of the page.

I saw this is also the case for the example document: https://karl-voit.at/tagstore/downloads/Voit2012b.pdf

Where am I wrong? Or is this indeed a problem with the template?

**Comment by mike-landl** [comment]
This can be explained if you view the right margin of the left page and the left margin of the right page as one combined center margin. In that case all 3 margins should be equally sized. You still need to consider a binding correction, which unfortunatley is not trivial to determine.

**Comment by stefanbschneider** [comment]
Ah ok. Can I manually set an extra binding correction margin in the template somehow? The size of the margin probably depends on how I'll bind the final book.

**Comment by mike-landl** [comment]
Yes, you can consider the binding correction in the template.

See code line 37 in the main.tx file:
"\newcommand{\myBCOR}{0mm}"

**Comment by stefanbschneider** [comment]
Ok, thanks!
