### ISSUE TITLE
Using Vietnamese in the document

### ISSUE THREAD

**Issue by torannn** [novoid/LaTeX-KOMA-template#37]
How can I load the Vietnamese language, please? I tried to adjust `\newcommand{\mylanguage}{ngerman,american}` into `\newcommand{\mylanguage}{ngerman,american, vietnamese}` but it has a bunch of errors (302 errors), mainly from error with csquote and bib.

**Comment by novoid** [comment]
I'm sorry, I can not help you with that with that error.

This is not an issue of the template itself but an issue with the babel package. You need to adapt `template/preamble.tex` where the value of "mylanguage" is actually used (single spot).

Maybe you can fix your issue by consulting the documentation of babel?

I wish you all the best.

**Comment by novoid** [comment]
As I thought about your issue afterward, I remembered that the main language of your document is the last language in the list. So if you only want to add some minor parts in Vietnamese and your main language is, e.g., "american", then you should try "vietnamese,american".

I can imagine that with Vietnamese as main language you might run into issues with csquote (what's the default way of quoting in Vietnamese?) as well as bib (what's the translation for "author" and other stuff?) in case Vietnamese translations are not that common yet.

HTH
