### ISSUE TITLE
Overfull boxes

### ISSUE THREAD

**Issue by kazemakase** [novoid/LaTeX-KOMA-template#5]
Thank you for this great template!

There  are overfull boxes in the statutory declaration (the lines for the signatures extend into the margin). 
Furthermore, the German version is shiftet to the right because "Graz, am" is longer than "Graz". Maybe it's also possible to horizontally align the English and the German signature blocks?

Please let me know if you want me to try and fix that in a pull request.

There are more overfull boxes in the Language and Writing Style section, but I don't really care about those :)

**Comment by novoid** [comment]
I think I did not get the email. Can you please resend it?

**Comment by kazemakase** [comment]
I may not have your correct email address, so I created a private repository instead and gave you access. Please let me know when you obtained the file so I can remove it again.
https://github.com/kazemakase/titlepage

I only have the dissertation template since I no longer have access to my TUG email account with the original email.

The template looks horrible, so I used my own not-quite-look-alike latex version, which is based on your titlepage template. I put the .tex into the repository too, in case you're interested.

**Comment by novoid** [comment]
Thanks for the pointer!

Did TUG change their specification on how to use the logo correctly? In 2012, it was strictly forbidden to use the TUG logo in the center. It had to be x mm from top and y mm from the right corner (can't remember x and y).

And yeah, usually, templates from authorities look horrible. No sense of typography, style, or page areas.

**Comment by kazemakase** [comment]
I guess the 2012 rules still apply. However, I believe the guideline says *preferably* upper right, so it could be ok to place the logo in the center.

**Comment by novoid** [comment]
I've cloned your private repos. You can get rid of it. Thanks!

**Comment by novoid** [comment]
I added your titlepage to the repository and to the documentation. Thanks for contributing!

**Comment by stefan2904** [comment]
The new titlepage is in German ... 
And uses new variables which are not in `main.text` ...

Does this make sense? I assumed the only thing that changed is the position of the logo?

**Comment by novoid** [comment]
Hi Stefan,

I can't follow your comment.

What do you mean by "The new titlepage is in German"? The title-page of my template is in German?

What "new variables" are not in `main.tex`?

And no: there were more changes than just the position of the logo: https://github.com/novoid/LaTeX-KOMA-template/commit/69e8901301ad9b2bc25b3c80261ebdb3e6495758
